### ISSUE TITLE
Upgrade Sentry dependency for `feedback_sentry`

### ISSUE THREAD

**Issue by Hamlet626** [ueman/feedback#218]
Could the developer upgrade the dependency to make it compatible with sentry 7.0.0? Thanks very much.

**Comment by mikhael28** [comment]
I am going to plus one this, but mostly because it's dependency on `intl` 0.17.0 is blocking my upgrade to `jiffy` 6.0 as well.

**Comment by ueman** [comment]
Is anyone of you willing to contribute this as a PR?

**Comment by mikhael28** [comment]
@Hamlet626 if you are looking for open-source exposure (idk if you are already working in the industry, your GitHub profile is light on commits) then I recommend you take this on. Otherwise, I can do this at some point - though @ueman your deps need to be updated across the board, not just in the sentry package I think. Also, it would be good for @Hamlet626 to check for Dart 3.0 compatibility (even though it's in alpha, check for build issues).

**Comment by ueman** [comment]
I've fixed most issues, so expect a new version soon-ish.

**Comment by ueman** [comment]
It's fixed in `feedback_sentry: ^2.4.0`
